# Generated by Django 3.2.5 on 2021-08-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagedataaccess",
            name="authority",
        ),
        migrations.AddField(
            model_name="messagedataaccess",
            name="message_recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="msgs.messagerecipient",
                verbose_name="Message recipient",
            ),
            preserve_default=False,
        ),
    ]
