# Generated by Django 3.2.6 on 2021-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=128),
            preserve_default=False,
        ),
    ]
