# Generated by Django 3.2.6 on 2021-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_data_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecategory',
            options={'verbose_name': 'Message Category', 'verbose_name_plural': 'Message Categories'},
        ),
        migrations.AlterField(
            model_name='messagecategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
