# Generated by Django 3.2.5 on 2021-08-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0003_message_rel_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sent on"),
        ),
    ]
