# Generated by Django 3.2.6 on 2021-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0008_auto_20210816_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="kind",
            field=models.CharField(
                choices=[
                    ("RECIPIENT", "Recipient (to)"),
                    ("CC", "Carbon Copy (cc)"),
                    ("SENDER", "Sender"),
                ],
                max_length=32,
            ),
        ),
    ]
