# Generated by Django 3.2.6 on 2021-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0009_alter_participant_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="available_to_sender",
            field=models.BooleanField(
                default=True,
                help_text="The message is also encrypted with the sender's public key. \n            You need to select this to be able to see the data of your message.",
                verbose_name="Message is available to sender",
            ),
        ),
    ]
