# Generated by Django 3.2.6 on 2021-09-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0013_auto_20210819_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[("NEW", "New"), ("REPLY", "Reply"), ("FIX", "Fix")],
                help_text="If you select Reply or Fix you must also select the related message to which you reply or fix",
                max_length=32,
                verbose_name="Message status",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("SENT", "Sent")],
                default="DRAFT",
                max_length=32,
                verbose_name="Message status",
            ),
        ),
    ]
