# Generated by Django 3.2.6 on 2021-08-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorities', '0003_authority_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('key', models.TextField(help_text='Please paste the key text in armored format ASCII', verbose_name='Key text')),
                ('fingerprint', models.CharField(help_text='The fingerprint of the key will be automatically generated after the key is validated', max_length=128, unique=True, verbose_name='Key fingerprint')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status of key', max_length=10, verbose_name='Status')),
                ('confirmation_document', models.FileField(upload_to='public/confirmations/%Y/%m/%d/', verbose_name='Confirmation document')),
                ('approved_on', models.DateTimeField(blank=True, null=True, verbose_name='Approval date')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorities.authority')),
            ],
            options={
                'verbose_name': 'Public key',
                'verbose_name_plural': 'Public keys',
            },
        ),
    ]
