# Generated by Django 3.2.6 on 2021-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='fingerprint',
            field=models.CharField(help_text='The fingerprint of the key', max_length=128, unique=True, verbose_name='Key fingerprint'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(help_text='The key text in armored ASCII format', verbose_name='Key text'),
        ),
    ]
