# Generated by Django 3.2.5 on 2021-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivation date'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='rejected_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejection date'),
        ),
    ]
