# Generated by Django 3.2.6 on 2021-08-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0005_auto_20210812_0904'),
        ('keys', '0003_alter_publickey_confirmation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authorities.authority', verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], default='NEW', help_text='Approval status of key', max_length=10, verbose_name='Status'),
        ),
    ]
